CREATE TYPE p_role AS ENUM('client', 'manager');

CREATE TABLE person (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(45) NOT NULL,
  surname bigint NOT NULL,
  phone varchar(13) NOT NULL,
  email varchar(45) NOT NULL UNIQUE,
  password varchar(45) NOT NULL,
  role p_role DEFAULT 'client',
  PRIMARY KEY (id)
);

CREATE TABLE address (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  street varchar(45) NOT NULL,
  house varchar(45) NOT NULL,
  flat int DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE custom (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  price int DEFAULT 0,
  address_id int NOT NULL,
  person_id int NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (address_id)
      REFERENCES address (id),
  FOREIGN KEY (person_id)
      REFERENCES person (id)
);

CREATE TABLE menu (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(45) DEFAULT NULL,
  price int DEFAULT 0,
  availability boolean DEFAULT false,
  demand boolean DEFAULT false,
  PRIMARY KEY (id)
);

CREATE TABLE product (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(45) DEFAULT NULL,
  price int DEFAULT NULL,
  weight int DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ingredient (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  weight int NOT NULL,
  percent int NOT NULL DEFAULT 20,
  menu_id int NOT NULL,
  product_id int NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (menu_id)
      REFERENCES menu (id),
  FOREIGN KEY (product_id)
      REFERENCES product (id)
);

CREATE TABLE details (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  quantity int DEFAULT 1,
  custom_id int NOT NULL,
  menu_id int NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (custom_id)
      REFERENCES custom (id),
  FOREIGN KEY (menu_id)
      REFERENCES menu (id)
);